- name: Create Jenkins Job
  hosts: localhost
  roles:
    - jenkins
  vars:
    mjobs:
      - { job_name: "cart" , repo_name: "https://github.com/ptammala/cart" }
    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/ptammala/roboshop-terraform" }