- name: Create Jenkins Job
  hosts: localhost
  roles:
    - jenkins
  vars:
    folders:
      - { folder_name: "CI-Pipelines"}
      - { folder_name: "Infra-Jobs"}
    mjobs:
      - { job_name: "cart" , repo_name: "https://github.com/ptammala/cart", folder_name: "CI-Pipelines" }
      - { job_name: "catalogue" , repo_name: "https://github.com/ptammala/cart", folder_name: "CI-Pipelines" }
      - { job_name: "user" , repo_name: "https://github.com/ptammala/cart", folder_name: "CI-Pipelines" }
      - { job_name: "payment" , repo_name: "https://github.com/ptammala/cart", folder_name: "CI-Pipelines" }
      - { job_name: "shipping" , repo_name: "https://github.com/ptammala/cart", folder_name: "CI-Pipelines" }
      - { job_name: "frontend" , repo_name: "https://github.com/ptammala/cart", folder_name: "CI-Pipelines" }
    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/ptammala/roboshop-terraform",folder_name: "Infra-Jobs" }