- name: Copy Config file
  ansible.builtin.templates:
    src: sjob.xml
    dest: /tmp/sjob.xml

- name: Create a Job - {{ item.job_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', /tmp/sjob.xml) }}"
    name: { { item.job_name } }
    password: admin123
    url: http://172.31.26.217:8080
    user: admin